org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=/data/data/com.termux/files/usr/lib/jvm/java-17-openjdk
android.useAndroidX=true
android.enableJetifier=true

hermesEnabled=false
newArchEnabled=true
